USE currency_service_db;

INSERT INTO currencies (name, long_name) VALUES ("AED", "United Arab Emirates Dirham");
INSERT INTO currencies (name, long_name) VALUES ("AUD", "Australian Dollar");
INSERT INTO currencies (name, long_name) VALUES ("BGN", "Bulgarian Lev");
INSERT INTO currencies (name, long_name) VALUES ("BTC", "Bitcoin");
INSERT INTO currencies (name, long_name) VALUES ("BYN", "Belarusian Ruble");
INSERT INTO currencies (name, long_name) VALUES ("CHF", "Swiss Franc");
INSERT INTO currencies (name, long_name) VALUES ("CNY", "Chinese Yuan");
INSERT INTO currencies (name, long_name) VALUES ("EUR", "Euro");
INSERT INTO currencies (name, long_name) VALUES ("GBP", "British Pound Sterling");
INSERT INTO currencies (name, long_name) VALUES ("GEL", "Georgian Lari");
INSERT INTO currencies (name, long_name) VALUES ("HKD", "Hong Kong Dollar");
INSERT INTO currencies (name, long_name) VALUES ("HRK", "Croatian Kuna");
INSERT INTO currencies (name, long_name) VALUES ("ILS", "Israeli New Sheqel");
INSERT INTO currencies (name, long_name) VALUES ("INR", "Indian Rupee");
INSERT INTO currencies (name, long_name) VALUES ("IQD", "Iraqi Dinar");
INSERT INTO currencies (name, long_name) VALUES ("IRR", "Iranian Rial");
INSERT INTO currencies (name, long_name) VALUES ("JPY", "Japanese Yen");
INSERT INTO currencies (name, long_name) VALUES ("KRW", "South Korean Won");
INSERT INTO currencies (name, long_name) VALUES ("MDL", "Moldovan Leu");
INSERT INTO currencies (name, long_name) VALUES ("MXN", "Mexican Peso");
INSERT INTO currencies (name, long_name) VALUES ("NOK", "Norwegian Krone");
INSERT INTO currencies (name, long_name) VALUES ("NZD", "New Zealand Dollar");
INSERT INTO currencies (name, long_name) VALUES ("PLN", "Polish Zloty");
INSERT INTO currencies (name, long_name) VALUES ("RON", "Romanian Leu");
INSERT INTO currencies (name, long_name) VALUES ("RUB", "Russian Ruble");
INSERT INTO currencies (name, long_name) VALUES ("SEK", "Swedish Krona");
INSERT INTO currencies (name, long_name) VALUES ("SGD", "Singapore Dollar");
INSERT INTO currencies (name, long_name) VALUES ("TRY", "Turkish Lira");
INSERT INTO currencies (name, long_name) VALUES ("TWD", "New Taiwan Dollar");
INSERT INTO currencies (name, long_name) VALUES ("UAH", "Ukrainian Hryvnia");
INSERT INTO currencies (name, long_name) VALUES ("USD", "United States Dollar");
INSERT INTO currencies (name, long_name) VALUES ("XAG", "Silver Ounce");
INSERT INTO currencies (name, long_name) VALUES ("XAU", "Gold Ounce");
INSERT INTO currencies (name, long_name) VALUES ("XPD", "Palladium Ounce");
INSERT INTO currencies (name, long_name) VALUES ("XPT", "Platinum Ounce");
INSERT INTO currencies (name, long_name) VALUES ("ZAR", "South African Rand");